OPENAI_API_KEY: "<OPENAI_API_KEY>"
CHAT_API_BASE: "https://api.openai.com/v1/chat/completions"
INSTRUCTION_API_BASE: "https://api.openai.com/v1/instruct/completions"
CHAT_ASSISTANT_ID: "<CHAT_ASSISTANT_ID>"
MODEL: "gpt-4-turbo" # or gpt-3.5-turbo
FILE_IDS: ["<FILE_ID>"]
